// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Remove the following hard-coded options before release.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJnHV9rsBXVIwP4JKyOtqi54ovpz0FP-w',
    appId: '1:519595634736:web:87bcf2618856fa50c7bdf5',
    messagingSenderId: '519595634736',
    projectId: 'regroup-c4089',
    authDomain: 'regroup-c4089.firebaseapp.com',
    storageBucket: 'regroup-c4089.appspot.com',
    measurementId: 'G-6GVDQ6FP4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9L7ion2CHUr8dlEl7p0D6iX8XhzT_W_g',
    appId: '1:519595634736:android:e8246d2ec815c3c5c7bdf5',
    messagingSenderId: '519595634736',
    projectId: 'regroup-c4089',
    storageBucket: 'regroup-c4089.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfS2HeBcVK-kcxYErLLF-TwpcEO_UsS_c',
    appId: '1:519595634736:ios:9f4f7de39438fc7cc7bdf5',
    messagingSenderId: '519595634736',
    projectId: 'regroup-c4089',
    storageBucket: 'regroup-c4089.appspot.com',
    iosClientId:
        '519595634736-n1mue9gkt228d0hof55u46n51unq2mav.apps.googleusercontent.com',
    iosBundleId: 'com.example.regroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfS2HeBcVK-kcxYErLLF-TwpcEO_UsS_c',
    appId: '1:519595634736:ios:9f4f7de39438fc7cc7bdf5',
    messagingSenderId: '519595634736',
    projectId: 'regroup-c4089',
    storageBucket: 'regroup-c4089.appspot.com',
    iosClientId:
        '519595634736-n1mue9gkt228d0hof55u46n51unq2mav.apps.googleusercontent.com',
    iosBundleId: 'com.example.regroup',
  );
}
